[package]
name = "invoke"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
log = "0.4.20"
cni-core = { path = "../cni-core" }
serde = { version = "1.0.192", features = ["derive"] }
serde_json = "1.0.108"
